version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achat_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-timesheet:
    depends_on:
      - mysqldb
    image: malekamri24/tp-foyer 
    #build : ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achat_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
      

    prometheus:
      image: prom/prometheus:latest
      restart: unless-stopped
      ports:
        - "9090:9090"  # Port pour accéder à l'interface utilisateur de Prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Assurez-vous que ce fichier existe
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'  # Spécifie le fichier de configuration
  
    grafana:
      image: grafana/grafana:latest
      restart: unless-stopped
      ports:
        - "3000:3000"  # Port pour accéder à l'interface utilisateur de Grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin  # Mot de passe admin par défaut
      depends_on:
        - prometheus  # Assurez-vous que Prometheus est prêt avant de démarrer Grafana
  
  volumes:
    db:
